main:
	make -C ../demo_sources/licence main
	make -C ../demo_sources/licence2 main
	make -C ../demo_sources/licence3 main
	cp ../demo_sources/licence/licence .
	cp ../demo_sources/licence2/licence2 .
	cp ../demo_sources/licence3/licence3 .